### ISSUE TITLE
What is the state of Tempo

### ISSUE THREAD

**Issue by Arakistech** [rrainey/tempo#1]
Hi! Very nice work. I am interesting in making some Tempo boards and tinkering with firmware. What is its current state? Is the operation stable?

Regards, 

Ivan

**Comment by rrainey** [comment]
Hi Ivan,
I had several of the current tempo board version assembled through PCBWay back in February.  They worked as expected with no issues. 

I've been in the process of switching from a pure Arduino stack to PlatformIO - the firmware I have running needs to be republished.  I have some time this weekend, so I might work on that -- the tempo board is a follow-on to my original "dropkick" project. One of the objectives for the switch was to get a fully open source, real-time pose estimator integrated. I'm using Madgwick's Fusion package for that functionality (https://github.com/xioTechnologies/Fusion).  The firmware availability is mostly a matter of me committing some working code at this point. Let me see how much progress I can make this weekend on things and I'll report back.

**Comment by rrainey** [comment]
With any luck, I should be able to post the complete logging application sometime over the weekend.

**Comment by rrainey** [comment]
The tempo-logger pio/Arduino sketch is in the final stages of debugging.  I am currently working on tuning the Fusion API interface.

**Comment by rrainey** [comment]
I will tag a release once I have a completely tested configuration.

**Comment by Arakistech** [comment]
Hi Riley,
Do you have any Tempo unit to sell?

Regards;
Ivan

**Comment by rrainey** [comment]
FWIW, I have not tagged a release, but the tempo-logger code looks good to go -- I plan to test it this weekend.
